# This is the config file, save and exit to confirm configuration.

# decks: 2 - 6
decks = 2

# sleep: 0.0 - 5.0
sleep = 3.0

# does not support infinite loop, round >= 1
rounds = 2

# no prompt for next round
yes = false

# show e-max
assist = true

# basically x-ray
debug = false

# just don't touch this
viewer = "cli"

[[players]]
name = "player-1"
algorithm = "basic 1"
user = true

[[players]]
name = "player-2"
algorithm = "x-ray"

[[players]]
name = "USER"
algorithm = "user"

[[players]]
name = "dealer"
algorithm = "dealer"
